name: flutter_version_override
description: A CLI tool to override pubspec version using an env YAML.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  yaml_edit: ^2.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  fvo: flutter_version_override